[2018-09-03 11:18:39,460] {cli.py:374} INFO - Running on host MacBook-Pro-de-MANGANNEAU.local
[2018-09-03 11:18:39,474] {models.py:1197} INFO - Dependencies all met for <TaskInstance: workshop_airflow_exo_1.get_data_from_api 2018-09-03 09:18:34.917202 [queued]>
[2018-09-03 11:18:39,477] {models.py:1197} INFO - Dependencies all met for <TaskInstance: workshop_airflow_exo_1.get_data_from_api 2018-09-03 09:18:34.917202 [queued]>
[2018-09-03 11:18:39,477] {models.py:1407} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 1
--------------------------------------------------------------------------------

[2018-09-03 11:18:39,482] {models.py:1428} INFO - Executing <Task(SimpleHttpOperator): get_data_from_api> on 2018-09-03 09:18:34.917202
[2018-09-03 11:18:39,483] {base_task_runner.py:115} INFO - Running: ['bash', '-c', 'airflow run workshop_airflow_exo_1 get_data_from_api 2018-09-03T09:18:34.917202 --job_id 3 --raw -sd DAGS_FOLDER/exo1.py']
[2018-09-03 11:18:40,146] {base_task_runner.py:98} INFO - Subtask: [2018-09-03 11:18:40,145] {__init__.py:45} INFO - Using executor SequentialExecutor
[2018-09-03 11:18:40,194] {base_task_runner.py:98} INFO - Subtask: [2018-09-03 11:18:40,194] {models.py:189} INFO - Filling up the DagBag from /Users/magus/PycharmProjects/workshop_airflow/dags/exo1.py
[2018-09-03 11:18:40,266] {cli.py:374} INFO - Running on host MacBook-Pro-de-MANGANNEAU.local
[2018-09-03 11:18:40,279] {base_task_runner.py:98} INFO - Subtask: [2018-09-03 11:18:40,279] {http_operator.py:77} INFO - Calling HTTP method
[2018-09-03 11:18:40,285] {models.py:1595} ERROR - The conn_id `navitia` isn't defined
Traceback (most recent call last):
  File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/models.py", line 1493, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/operators/http_operator.py", line 82, in execute
    self.extra_options)
  File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 62, in run
    session = self.get_conn(headers)
  File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 37, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 77, in get_connection
    conn = random.choice(cls.get_connections(conn_id))
  File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 72, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 55, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `navitia` isn't defined
[2018-09-03 11:18:40,289] {models.py:1624} INFO - Marking task as FAILED.
[2018-09-03 11:18:40,297] {models.py:1644} ERROR - The conn_id `navitia` isn't defined
[2018-09-03 11:18:40,299] {base_task_runner.py:98} INFO - Subtask: Traceback (most recent call last):
[2018-09-03 11:18:40,299] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/bin/airflow", line 27, in <module>
[2018-09-03 11:18:40,299] {base_task_runner.py:98} INFO - Subtask:     args.func(args)
[2018-09-03 11:18:40,299] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/bin/cli.py", line 392, in run
[2018-09-03 11:18:40,299] {base_task_runner.py:98} INFO - Subtask:     pool=args.pool,
[2018-09-03 11:18:40,299] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/utils/db.py", line 50, in wrapper
[2018-09-03 11:18:40,299] {base_task_runner.py:98} INFO - Subtask:     result = func(*args, **kwargs)
[2018-09-03 11:18:40,300] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/models.py", line 1493, in _run_raw_task
[2018-09-03 11:18:40,332] {base_task_runner.py:98} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-09-03 11:18:40,332] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/operators/http_operator.py", line 82, in execute
[2018-09-03 11:18:40,332] {base_task_runner.py:98} INFO - Subtask:     self.extra_options)
[2018-09-03 11:18:40,332] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 62, in run
[2018-09-03 11:18:40,332] {base_task_runner.py:98} INFO - Subtask:     session = self.get_conn(headers)
[2018-09-03 11:18:40,332] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 37, in get_conn
[2018-09-03 11:18:40,332] {base_task_runner.py:98} INFO - Subtask:     conn = self.get_connection(self.http_conn_id)
[2018-09-03 11:18:40,333] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 77, in get_connection
[2018-09-03 11:18:40,333] {base_task_runner.py:98} INFO - Subtask:     conn = random.choice(cls.get_connections(conn_id))
[2018-09-03 11:18:40,333] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 72, in get_connections
[2018-09-03 11:18:40,333] {base_task_runner.py:98} INFO - Subtask:     conns = cls._get_connections_from_db(conn_id)
[2018-09-03 11:18:40,333] {base_task_runner.py:98} INFO - Subtask:   File "/Users/magus/PycharmProjects/workshop_airflow/workshop_env/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 55, in _get_connections_from_db
[2018-09-03 11:18:40,333] {base_task_runner.py:98} INFO - Subtask:     "The conn_id `{0}` isn't defined".format(conn_id))
[2018-09-03 11:18:40,333] {base_task_runner.py:98} INFO - Subtask: airflow.exceptions.AirflowException: The conn_id `navitia` isn't defined
